config/routes.rb
Goalkeepr::Application.routes.draw do
  get "pages/home"

  devise_for :users
  resources :goals, :only => [:index, :create, :destroy] do
    post 'vote'
  end

  root :to => 'pages#home'
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :business_name

  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @goal = Goal.new
    @goals = current_user.goals.order("created_at ASC")
  end

  def create
    saved = false

    if params[:goal] && params[:goal][:due_date]
      params[:goal][:due_date] = params[:goal][:due_date].to_date
      goal = current_user.goals.new(params[:goal])

      if (saved = goal.save)
        redirect_to goals_path, :notice => "Goal created successfully!"
      end
    end
    redirect_to goals_path, :alert => "Unable to create goal." unless saved
  end

  def destroy
    goal = current_user.goals.find(params[:id])
    goal.destroy

    redirect_to goals_path, :notice => "Goal removed"
  end

  def vote
    goal = current_user.goals.find(params[:goal_id])
    goal.increment!(:votes)
    render :text => goal.votes
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/goals/index.html.haml
.page-header
  %h1 goalkeepr
  .business= current_user.business_name
  .clearfix

= simple_form_for @goal do |f|
  .inline-inputs
    = f.input :description, :as => :string, :placeholder => "Description", :label => false
    = f.input :due_date, :as => :string, :placeholder => "Due Date", :label => false, :input_html => {:data => { :datepicker => :datepicker }}
    = f.submit 'Create', :class => 'btn primary'

- @goals.each_with_index do |goal, i|
  .row
    .goal{'data-goal' => goal.id}
      #{i + 1}. #{goal.description}
      %span{:style =>'color:lightgrey;'} within #{distance_of_time_in_words(Time.now, goal.due_date)}
      #{goal.votes} votes
    .action= link_to 'Remove', goal_path(goal), :method => :delete, :style => 'color:red;'


:javascript
  $(document).ready(function () {
    $('.goal').click(function(e){
      goal_id = $(this).data('goal');
      url = '/goals/' + goal_id + '/vote';

      $.post(url, function(data) {
        location.reload();
      });
    });
  });


  /* Update datepicker plugin so that MM/DD/YYYY format is used. */
  $.extend($.fn.datepicker.defaults, {
    parse: function (string) {
      var matches;
      if ((matches = string.match(/^(\d{2,2})\/(\d{2,2})\/(\d{4,4})$/))) {
        return new Date(matches[3],matches[2] - 1, matches[1]);
      } else {
        return null;
      }
    },
    format: function (date) {
      var
        month = (date.getMonth() + 1).toString(),
        dom = date.getDate().toString();
      if (month.length === 1) {
        month = "0" + month;
      }
      if (dom.length === 1) {
        dom = "0" + dom;
      }
      return dom + "/" + month + "/" + date.getFullYear();
    }
  });

app/views/layouts/application.html.haml
!!! 5
%head
  %title goalkeepr
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body{ :id => params[:controller].parameterize.split('-').last, :class => params[:action].parameterize }
  .container
    .content
      = yield

app/views/pages/home.html.haml
.row
  %h1 goalkeepr

.row
  %p.info
    An experiment in goal setting and monitoring
    %br
    by #{ link_to 'Semblance Systems', 'http://semblancesystems.com' }
.row
  = button_to 'Get Started', goals_path, :class => 'btn primary', :method => :get